"""organizations RLS: deferred since migration 0001 (see that file's
docstring on `organizations` — the tenant root never got a policy because
it collided with the login-bootstrap problem user_lookup exists to solve).
Resolved now that invites make multi-org membership real: a compromised or
misused wrkbase_app connection could otherwise enumerate every
organization's name with no tenant filtering at all.

Revision ID: 0015
Revises: 0014
Create Date: 2026-07-08

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

revision: str = "0015"
down_revision: Union[str, None] = "0014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    bind.execute(text("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY"))
    bind.execute(text("ALTER TABLE organizations FORCE ROW LEVEL SECURITY"))

    # organizations has no org_id column — a row here IS the tenant, not
    # something that belongs to one. Every other policy in this app reads
    # "org_id = current tenant context"; this one has to read
    # "id = current tenant context" instead, because id is the only column
    # that identifies which tenant a row is.
    #
    # That single difference is also why this table needs three separate
    # per-command policies instead of one USING+WITH CHECK pair like
    # `sprints` (migration 0012) or `users` (migration 0001):
    #
    #   - SELECT is scoped: org A must never read org B's row by id, even
    #     though nothing about the query "knows" it's guessing at another
    #     tenant's row. Same default-deny shape as everywhere else.
    #
    #   - INSERT has to stay permissive (WITH CHECK true). Self-serve
    #     signup (app/api/auth.py's signup()) and scripts.seed both create
    #     the Organization row *before* any tenant context exists — id is
    #     server-generated by gen_random_uuid() and isn't known until the
    #     INSERT itself completes, so a WITH CHECK keyed on "id = current
    #     context" is impossible to satisfy at insert time. A restrictive
    #     INSERT policy would make it impossible to ever create the first
    #     org. This isn't a workaround: an INSERT can't leak existing rows
    #     the way SELECT/UPDATE can, and unrestricted self-serve org
    #     creation is already this app's intentional behavior.
    #
    #   - UPDATE is scoped like SELECT, not left permissive like INSERT.
    #     app/api/tickets.py's _next_ticket_number() runs
    #     `UPDATE organizations ... WHERE id = :org_id RETURNING ...` on
    #     every single ticket creation — the org's own counter, always
    #     under its own already-set tenant context. Without this policy,
    #     FORCE ROW LEVEL SECURITY defaults to deny for any command with
    #     no applicable policy, which would silently break every ticket
    #     creation (the UPDATE would match zero rows and
    #     `result.scalar_one()` would raise). Scoping it also means org A
    #     can never bump org B's counters, which a permissive policy here
    #     would otherwise allow.
    #
    #   - DELETE is deliberately left with no policy at all (default-deny
    #     under FORCE RLS). No code path in this app ever deletes an
    #     organization row, so there's nothing to make permissive, and
    #     leaving it unpoliced means that stays true even if someone
    #     forgets to think about it later.
    bind.execute(
        text(
            """
            CREATE POLICY select_own_org ON organizations
            FOR SELECT
            USING (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            """
        )
    )
    bind.execute(
        text(
            """
            CREATE POLICY insert_new_org ON organizations
            FOR INSERT
            WITH CHECK (true)
            """
        )
    )
    bind.execute(
        text(
            """
            CREATE POLICY update_own_org ON organizations
            FOR UPDATE
            USING (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            WITH CHECK (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            """
        )
    )


def downgrade() -> None:
    bind = op.get_bind()

    bind.execute(text("DROP POLICY IF EXISTS update_own_org ON organizations"))
    bind.execute(text("DROP POLICY IF EXISTS insert_new_org ON organizations"))
    bind.execute(text("DROP POLICY IF EXISTS select_own_org ON organizations"))
    bind.execute(text("ALTER TABLE organizations NO FORCE ROW LEVEL SECURITY"))
    bind.execute(text("ALTER TABLE organizations DISABLE ROW LEVEL SECURITY"))
